---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/26 4:02 PM
---

package.path = package.path .. ";../?.lua;"

local CfoxRecv = require("beeQ.foxRecv")
local unistd = require("posix.unistd")


local fox

function init(tid, fYaml)
    fYaml = fYaml or "../collector/plugin.yaml"
    fox = CfoxRecv.new(fYaml)
    print(string.format("hello beeQ, pid: %d, tid: %d", unistd.getpid(), tid))
    return 0
end

function proc(stream)
    fox:write(stream)
    return 0
end
