---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/26 11:26 PM
---
package.path = package.path .. ";../common/?.lua;"
package.path = package.path .. ";../collector/?.lua;"
package.path = package.path .. ";../collector/native/?.lua;"

local Cloop = require("loop")
local system = require("system")

workLoop = nil

function init(que, proto_q, t)
    local work = Cloop.new(que, proto_q)
    workLoop = work
    return 0
end

function work(t)
    workLoop:work(t)
    return 0
end
