---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/26 3:57 PM
---

require("common.class")

local CfoxTSDB = require("tsdb.foxTSDB")

local CfoxRecv = class("CfoxRecv")

function CfoxRecv:_init_(fYaml)
    self._fox = CfoxTSDB.new(fYaml)
    self._fox:setupWrite()
end

function CfoxRecv:write(stream)
    self._fox:write(stream)
end

return CfoxRecv
