---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/2/16 11:29 PM
---

package.path = package.path .. ";../?.lua;"

local CpipeMon = require("collector.outline.pipeMon")

local pipe = nil

function init(que, fYaml)
    local fYaml = fYaml or "../collector/plugin.yaml"
    pipe = CpipeMon.new(que, fYaml)
    if pipe then
        return 0
    end
end

function work()
    return pipe:poll()
end
