---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/7 01:36
---

package.path = package.path .. ";../?.lua;"

local unistd = require("posix.unistd")

function work(fd, fYaml)
    while true do
        local s, err, errno = unistd.read(fd, 1024 * 1024)
        if s then
            print(string.format("recv %d bytes.", #s))
        else
            print(err, errno)
            break
        end
    end
    print("end push.")
    return 0
end
