---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:20 AM
---

require("class")
local Cbase = require("base")

Cone = class("one", Cbase)

function Cone:_init_(name)
    Cbase._init_(self, name)
end

function Cone:say()
    print("one say " .. self.name)
end

return Cone
