---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:33 AM
---
---
require("class")
local Cone = require("one")

CTwo = class("two", Cone)

function CTwo:_init_(name)
    Cone._init_(self, name)
end

function CTwo:say()
    print("two say " .. self.name)
    print("super")
    Cone.say(self)
end

return CTwo