---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:59 PM
---

package.path = package.path .. ";../common/?.lua;"
package.path = package.path .. ";../collector/?.lua;"
package.path = package.path .. ";../collector/native/?.lua;"

local Cloop = require("loop")
local system = require("system")

local work = Cloop.new()
while true do
    work:work(1)
    system:sleep(1)
end