---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/17 10:22 AM
---

package.path = package.path .. ";../common/?.lua;"
package.path = package.path .. ";../tsdb/native/?.lua;"

local system = require("system")
local foxFFI = require("foxffi")

local us1 = foxFFI.cffi.get_us()
assert(us1 > 0)
local d1 = foxFFI.ffi.new("struct foxDate")
assert(foxFFI.cffi.get_date_from_us(us1, d1) == 0)
local us2 = foxFFI.cffi.make_stamp(d1)
local d2 = foxFFI.ffi.new("struct foxDate")
foxFFI.cffi.get_date_from_us(us2, d2)
assert(foxFFI.cffi.check_foxdate(d1, d2) == 1)

system:sleep(1)

us2 = foxFFI.cffi.get_us()
local delta = us2 - us1
assert(delta > 1000000)
assert(delta < 1100000)

assert(foxFFI.cffi.get_date(d2) == 0)
assert(d1.year <= d2.year)
if d1.year == d2.year then
    assert(d1.mon <= d2.mon)
    if d1.mon == d2.mon then
        assert(d1.mday <= d2.mday)
        if d1.mday == d2.mday then
            assert(d1.hour <= d2.hour)
            if d1.hour == d2.hour then
                assert(d1.min <= d2.min)
                if d1.min == d2.min then
                    assert(d1.sec < d2.sec)
                end
            end
        end
    end
end

local us3 = foxFFI.cffi.make_stamp(d2)
assert(us3 > us1)
assert(us3 <= us2)

print("native fox time ok.")
