---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/5/5 11:33
---

local stat = require("posix.sys.stat")

local res, err, errno = stat.stat("/proc/1/fd/36")
print(err, errno)
print(stat.S_ISSOCK(res.st_mode))
for a, b in pairs(res) do
    print(a, b)
end
