---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/17 11:39 AM
---

package.path = package.path .. ";../common/?.lua;"
package.path = package.path .. ";../tsdb/?.lua;"
package.path = package.path .. ";../tsdb/native/?.lua;"

local CfoxTSDB = require("foxTSDB")

local fox = CfoxTSDB.new()

local s1 = "2022-12-17 11:13:00"

local foxTime = fox:str2date(s1)
assert(foxTime.year == 2022 - 1900)
assert(foxTime.mon == 12 - 1)
assert(foxTime.mday == 17)
assert(foxTime.hour == 11)
assert(foxTime.min == 13)
assert(foxTime.sec == 0)

local sCheck = fox:date2str(foxTime)
assert(s1 == sCheck)

--local s1 = "2022-12-17 11:13:00"
local s2 = "2022-12-17 11:13:05"
sCheck = fox:movesSec(s1, 5)
assert(s2 == sCheck)
s2 = "2022-12-17 11:14:06"
sCheck = fox:movesSec(s1, 66)
assert(s2 == sCheck)
s2 = "2022-12-17 11:12:55"
sCheck = fox:movesSec(s1, -5)
assert(s2 == sCheck)

--local s1 = "2022-12-17 11:13:00"
s2 = "2022-12-17 11:12:55"
sCheck = fox:movesTime(s1, {sec=-5})
assert(s2 == sCheck)
s2 = "2022-12-07 11:12:55"
sCheck = fox:movesTime(s1, {sec=-5, day=-10})
assert(s2 == sCheck)
s2 = "2022-12-17 11:13:05"
sCheck = fox:movesTime(s1, {sec=5})
assert(s2 == sCheck)
s2 = "2022-12-17 11:15:05"
sCheck = fox:movesTime(s1, {sec=5, min=2})
assert(s2 == sCheck)
s2 = "2022-12-17 15:15:05"
sCheck = fox:movesTime(s1, {sec=5, min=2, hour=4})
assert(s2 == sCheck)
s2 = "2022-12-20 15:15:05"
sCheck = fox:movesTime(s1, {sec=5, min=2, hour=4, day=3})
assert(s2 == sCheck)


print("fox time ok.")

