---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/3 16:06
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local coHttpCli = require("httplib.coHttpCli")

local cli = coHttpCli.new("pylcc.openanolis.cn", 5008)
--local cli = coHttpCli.new("cn.bing.com")
cli:get()
