---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/10 12:01 AM
---

package.path = package.path .. ";../../?.lua;"

local api = require("httplib.dockerApi")
local system = require("common.system")

local d = api.new('localhost', '/mnt/host/var/run/docker.sock')
print(system:dump(d:list_containers({ all = 'true' })))
