---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/5/22 17:00
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local ChttpCli = require("httplib.httpCli")

local cli = ChttpCli.new()
local url = "http://127.0.0.1:8400/api/trig"
--local req = {cmd = "diag", exec = "io_hang", args = {"hangdetect", "vda"}}
local req = {cmd = "diag", exec = "net_edge", args = {"172.16.0.118", "host", "tcp port 80"}, uid = system:guid()}
local res = cli:postTable(url, req)
system:dumps(res)