---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/25 8:48 PM
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local ChttpCli = require("httplib.httpCli")

local url = "http://127.0.0.1:8400/api/404"
local cli = ChttpCli.new()
local formData = {
    hello = "world",
    file = {"a.out", "hello, world.", "application/octet-stream"}
}
system:dumps(cli:postFormData(url, formData))
