---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/27 11:46 PM
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local ChttpReq = require("httplib.httpReq")

local req = ChttpReq.new()

system:dumps(req:get("https://cn.bing.com/"))
