---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/28 7:55 AM
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local ChttpReq = require("httplib.httpReq")

local cli = ChttpReq.new()
local url = "http://127.0.0.1:8400/api/line"
local res = cli:postLine(url, "lineTable,index=abc value=1")
assert(res.code == "200")
system:dumps(res)
