---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/3 17:52
---

package.path = package.path .. ";../../?.lua;"

local system = require("common.system")
local unistd = require("posix.unistd")
local posix = require("posix")
local coCli = require("httplib.coCli")
local coHttpCli = require("httplib.coHttpCli")

local fdIn, fdOut = unistd.pipe()
local frame = coCli.new(fdIn)
local c = coHttpCli.new("cn.bing.com")
--local c = coHttpCli.new("pylcc.openanolis.cn", 5008)
frame:poll(c)
unistd.close(fdIn)
unistd.close(fdOut)
