---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/6 00:14
---

package.path = package.path .. ";../../?.lua;"
local unistd = require("posix.unistd")
local posix = require("posix")
local coCli = require("httplib.coCli")
local coInflux = require("httplib.coInflux")

local fdIn, fdOut = unistd.pipe()
local frame = coCli.new(fdIn)
local c = coInflux.new("ld-wz9d17b514mg6kjkx-proxy-tsdb.lindorm.rds.aliyuncs.com", 8242, "/api/v2/write?db=lua")
frame:poll(c)
unistd.close(fdIn)
unistd.close(fdOut)
