---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/29 11:01 PM
---
-- should ln -s liblz4.so.1 liblz4.so at first


package.path = package.path .. ";../../common/?.lua;"

local lz4 = require("lz4")

local s = "hello lz4, hello lz4, hello lz4, hello lz4, hello lz4, hello lz4"
local cmp = lz4.compress(s)
print(#s, #cmp)
