---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/26 10:24 PM
---

require("common.class")

local CtaskMons = require("collector.postPlugin.taskMons")
local CpostPlugin = class("")

function CpostPlugin:_init_(proto, pffi, mnt)
    self.tasks = CtaskMons.new(proto, pffi, mnt)
end

function CpostPlugin:proc(elapsed, lines)
    self.tasks:proc(elapsed, lines)
end

return CpostPlugin
