---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/2/28 11:00 PM
---

local reFmt = "[\\`%*_%{%}%[%]%(%)#%+%-%.!|]"
local reHtml = '[<>&"\t]'

local htmlRep  = {
    ["<"] = function() return "&lt;" end,
    [">"] = function() return "&gt;" end,
    ["&"] = function() return "&amp;" end,
    ['"'] = function() return "&quot;" end,
    ["\t"] = function() return "&emsp;" end,
}

local function escape(s)
    return htmlRep[s]()
end

local function pEscape(s)
    return string.gsub(s, reHtml, function(s) return escape(s)  end)
end

local function escMd(s)
    return "\\" .. s
end

local function pEscMd(s)
    return string.gsub(s, reFmt, function(s) return escMd(s)  end)
end

local s = "<hello&\t\">"
print(pEscape(s))

s = "\\`.*_{}[]()#+-.|!"
print(#s)
print(pEscMd(s))

