---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/3 9:31 PM
---

package.path = package.path .. ";../../common/?.lua;"

local pystring = require("pystring")

-- 字符串分割，默认按照空格分割
local ret = pystring:split("hello lua language")
assert(#ret == 3)
assert(ret[1] == "hello")
assert(ret[2] == "lua")
assert(ret[3] == "language")
ret = pystring:split("hello lua language lua language")
assert(#ret == 5 )
assert(ret[1] == "hello")
assert(ret[2] == "lua")
assert(ret[3] == "language")
assert(ret[4] == "lua")
assert(ret[5] == "language")
ret = pystring:split("Node 0, zone      DMA      1      0      0      1      2      1      1      0      1      1      3")
assert(#ret == 15)

-- 自定符号分割
ret = pystring:split("hello*lua *language", "*")
assert(#ret == 3)
assert(ret[1] == "hello")
assert(ret[2] == "lua ")
assert(ret[3] == "language")

-- 从右边开始规定次数分割
ret = pystring:rsplit("hello*lua *language", "*", 1)
assert(#ret == 2)
assert(ret[1] == "hello*lua ")

-- 多字符串分割
ret = pystring:split("hello*lua *language", "*l")
assert(#ret == 3)
assert(ret[1] == "hello")
assert(ret[2] == "ua ")
assert(ret[3] == "anguage")

-- strip掉左右空格
assert(pystring:strip("\t hello world.  \t\n") == "hello world.")

-- strip掉左右指定符号
assert(pystring:strip("**hello world**", "*") == "hello world")

-- strip复合符号
assert(pystring:strip("*?hello world*?", "*?") == "hello world")

-- strip字符串
assert(pystring:strip("abcdefhello worldabcdef", "abcdef") == "hello world")

-- lstrip字符串
assert(pystring:lstrip("abcdefhello worldabcdef", "abcdef") == "hello worldabcdef")

-- rstrip字符串
assert(pystring:rstrip("abcdefhello worldabcdef", "abcdef") == "abcdefhello world")

-- join 连接
local s = "abc d ef g"
local ret = pystring:split(s)
assert(pystring:join(" ", ret) == s)

-- startswith/endswith
assert(pystring:startswith("hello world", "hello"))
assert(pystring:endswith("hello world", "world"))

-- find
assert(pystring:find("hello world.", "hello") == 1)
