---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/2/9 11:26 PM
---

package.path = package.path .. ";../../?.lua;"
local lineParse = require("common.lineParse")

local line = "hello v=3"
local title, ls, vs = lineParse.parse(line)
assert(title == "hello")
assert(vs.v == 3)
local cLine = lineParse.pack(title, ls, vs)
assert(cLine == line)

line = "hello,i=1,c=abc log=\"hello,\\\"world.\",v=3,b=4"
title, ls, vs = lineParse.parse(line)
assert(title == "hello")
assert(ls.i == "1")
assert(ls.c == "abc")
assert(vs.v== 3)
assert(vs.log == "hello,\"world.", vs.log)
assert(vs.b == 4)
local cLine = lineParse.pack(title, ls, vs)
assert(cLine == line)