---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/5/4 10:50
---

local unistd = require("posix.unistd")
local pwait = require("posix.sys.wait")
local signal = require("posix.signal")

local module = {}

function module.run(cmd, args)
    local pid, err = unistd.fork()
    if pid > 0 then   -- for self
        print("pid: " .. pid)
        return pid
    elseif pid == 0 then   -- for child
        local errno
        prctl_death_kill()
        _, err, errno = unistd.exec(cmd, args)
        assert(not errno, "exec failed." .. err .. errno)
    else
        error("fork report" .. err)
    end
end

function module.kill(pid)
    signal.kill(pid, signal.SIGKILL)  -- force to kill task
    pwait.wait(pid)                     -- wait task
end

return module
