---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/30 3:56 PM
---

package.path = package.path .. ";../../../common/?.lua;"
package.path = package.path .. ";../../../httplib/?.lua;"

local CslsCli = require("slsCli")

local cli = CslsCli.new("cn-heyuan.log.aliyuncs.com",
        "netinfo-heyuan", "moon",
        "key", "pswd")

cli:putLog("abc", "hello.")
