---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/30 3:56 PM
---

package.path = package.path .. ";../../../?.lua;"
package.path = package.path .. ";../../../?.lua;"

package.path = package.path .. ";../../../?.lua;"

local CslsCli = require("httplib.slsCli")

local lines = {}
for line in io.lines("config") do
    table.insert(lines, line)
end

local cli = CslsCli.new(lines[1], lines[2], lines[3], lines[4], lines[5])

cli:putLog({vm = "abc", log = "hello."})
