---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/24 11:13 PM
---

local mod = {}
local ffi = require("ffi")

ffi.cdef [[
int postQue_pull(char *msg);
int postQue_post(char *msg);
]]

local cffi = ffi.load("postQue")

function mod.pull()
    local s = self.ffi.new("char[?]", 1024)
    local ret = cffi.postQue_pull(s)
    if ret > 0 then
        return s
    end
    return nil
end

function mod.post(msg)
    return cffi.postQue_post(msg)
end

return mod