---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/24 11:13 PM
---

local mod = {}
local ffi = require("ffi")

ffi.cdef [[
int postQue_pull(char *msg, int size);
int postQue_post(const char *msg);
]]

local cffi = ffi.load("postQue")

function mod.pull()
    local len = 16*1024
    local s = ffi.new("char[?]", len)
    local ret = cffi.postQue_pull(s,len)
    if ret > 0 then
        return ffi.string(s)
    end
    return nil
end

function mod.post(msg)
    return cffi.postQue_post(msg)
end

return mod