---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/12 00:01
---

require("common.class")
local exec = require("common.exec")
local pwait = require("posix.sys.wait")
local pystring = require("common.pystring")
local system = require("common.system")

local CexecBase = class("execBase")
local interval = 5   --- poll for every 5 second

function CexecBase:_init_(cmd, args, seconds)
    self.cmd = cmd
    self._cnt = 0
    self._loop = seconds / interval

    self._pid = exec.run(cmd, args)
end

function CexecBase:addEvents(e)
    e:addEvent(self.cmd, self, interval, true, self._loop)
end

function CexecBase:work()
    local cnt = self._cnt
    if cnt >= self._loop then
        local pid, stat, exit = pwait.wait(self._pid, pwait.WNOHANG)
        if pid == nil then
            error("wait failed " .. stat .. exit)
        end
        if not exit then -- process not exit
            print("force to kill " .. self._pid)
            exec.kill(self._pid)
        end
        return -1  -- delete from task list.
    end
    self._cnt = cnt + 1
end

return CexecBase
