---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/5/3 23:04
---

require("common.class")
local unistd = require("posix.unistd")
local pwait = require("posix.sys.wait")
local signal = require("posix.signal")