---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/4 11:59 PM
---

package.path = package.path .. ";../../?.lua;"
local system = require("common.system")
local ptime = require("posix.time")

local function calcSleep(hope, now)
    if hope.tv_nsec >= now.tv_nsec then
        return {tv_sec  = hope.tv_sec - now.tv_sec,
                tv_nsec = hope.tv_nsec - now.tv_nsec}
    else
        return {tv_sec  = hope.tv_sec - now.tv_sec - 1,
                tv_nsec = 1e9 + hope.tv_nsec - now.tv_nsec}
    end
end

local unit = 5
local tStart = ptime.clock_gettime(ptime.CLOCK_MONOTONIC)
while true do
    local now = ptime.clock_gettime(ptime.CLOCK_MONOTONIC)
    local hope = {tv_sec = tStart.tv_sec + unit, tv_nsec = tStart.tv_sec}
    local diff = calcSleep(hope, now)
    assert(diff.tv_sec >= 0)
    print(system:dump(diff))
    local _, s, errno, _ = ptime.nanosleep(diff)
    if errno then
        print(string.format("new sleep stop. %d, %s", errno, s))
        break
    end
    tStart = hope
end


