---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/29 8:25 PM
---

require("common.class")
local CprotoData = require("common.protoData")
local CvProto = require("collector.vproto")
local CioDiagnose = class("ioDiagnose", CvProto)
local system = require("common.system")

function CioDiagnose:_init_(que, proto_q, fYaml, tid)
    CvProto._init_(self, CprotoData.new(que))
    self._tid  = tid
    local res = system:parseYaml(fYaml)
    self.pFile = res.config.proc_path .. "proc/stat"
end

function CioDiagnose:proc(t)

end

function CioDiagnose:work(t)

end
