---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wrp.
--- DateTime: 2023/7/20 17:10
--- 进程级主次缺页次数。主12，次10
---

require("common.class")

local CvProc = require("collector.vproc")
local system = require("common.system")
local pystring = require("common.pystring")

local CobFault = class("obFault",CvProc)


function CobFault:_init_(pid, proto, pffi, mnt, pFile)
    self._pid = pid
    CvProc._init_(self, proto, pffi, mnt, pFile or "proc/"..self._pid.."/stat")
    self._protoTable = {
        line = "observe",
        ls = { { name = "pid", index = tostring(pid) } },
        vs = {}
    }

end

function CobFault:proc(elapsed, lines)
    self._protoTable.vs = {}
    CvProc.proc(self)
    for line in io.lines(self.pFile) do

        local subline = pystring:split(line," ",13)
        local maj = subline[12]
        local min = subline[10]
        local cell1 = {name = "majflt",value = tonumber(maj)}
        table.insert(self._protoTable["vs"], cell1)
        local cell2 = {name = "minflt",value = tonumber(min)}
        table.insert(self._protoTable["vs"], cell2)
    end
    self:appendLine(self._protoTable)
    self:push(lines)
end

return CobFault