---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/2/13 3:34 PM
---

package.path = package.path .. ";../../../?.lua;"

local Cbeavers = require("beavers")

local bservers = Cbeavers.new()
bservers:poll()
