---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/19 3:36 PM
---

require("common.class")

local CcollectorStat = class("CcollectorStat")

return CcollectorStat