---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/22 11:05 PM
---

require("common.class")

local unistd = require("posix.unistd")
local system = require("common.system")
local CguardDaemon = class("guardDaemon")

local function feedDaemon(fd)
    local ws, err, errno = unistd.write(fd, "feed.")
    if ws == nil then
        system:posixError("feed daemon failed.", err, errno)
    end
end

function CguardDaemon:_init_(resYaml)
    local freq = resYaml.config.freq
    if resYaml.config.daemon then
        self.fd = lua_setup_daemon(freq)
        self.feedOnce = function()  feedDaemon(self.fd)  end
    else
        self.fd = -1
        self.feedOnce = function()  end
    end
end

function CguardDaemon:_del_()
    if self.fd > 0 then
        unistd.write(self.fd, "stop")
        unistd.close(self.fd)
    end
end

function CguardDaemon:feed()
    self.feedOnce()
end

return CguardDaemon
