---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/2 12:05 PM
---

require("common.class")
local pystring = require("common.pystring")
local ChttpHtml = require("httplib.httpHtml")

local CurlGuide = class("CurlIndex", ChttpHtml)

function CurlGuide:_init_(frame)
    ChttpHtml._init_(self)
    self:_installRe("^/guide*", frame)
    self._head = "/"   -- need to strip
    self._filePath = "../beaver/"
end

function CurlGuide:callRe(tReq, keep)
    return self:reSource(tReq, keep, self._head, self._filePath)
end

return CurlGuide
