---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/2 12:05 PM
---

require("class")
local ChttpHtml = require("httpHtml")

local CurlGuide = class("CurlIndex", ChttpHtml)

function CurlGuide:_init_(frame)
    ChttpHtml._init_(self)
    self._urlCb["/guide"] = function(tReq) return self:guide(tReq)  end
    self._urlCb["/guide/hotplugin"] = function(tReq) return self:hotplugin(tReq)  end
    self._urlCb["/guide/oop"] = function(tReq) return self:oop(tReq)  end
    self:_install(frame)
end

local function loadFile(fPpath)
    local path = "../beaver/guide/" .. fPpath
    print(path)
    local f = io.open(path,"r")
    local s = f:read("*all")
    f:close()
    return s
end

function CurlGuide:guide(tReq)
    return {title="guide", content=self:markdown(loadFile("guide.md"))}
end

function CurlGuide:hotplugin(tReq)
    return {title="hotplugin", content=self:markdown(loadFile("hotplugin.md"))}
end

function CurlGuide:oop(tReq)
    return {title="oop", content=self:markdown(loadFile("oop.md"))}
end

return CurlGuide
