---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/25 11:20 AM
---

require("common.class")
local ChttpPlain = require("httplib.httpPlain")

local CurlExportRaw = class("CurlExportRaw", ChttpPlain)

function CurlExportRaw:_init_(frame, export)
    ChttpPlain._init_(self)
    self._export = export

    self._urlCb["/export/metrics"] = function(tReq) return self:show(tReq)  end
    self._urlCb["/metrics"] = function(tReq) return self:show(tReq)  end
    self:_install(frame)
end

function CurlExportRaw:show(tReq)
    return {text = self._export:export()}
end

return CurlExportRaw
