---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/8 2:32 PM
---

require("common.class")
local pystring = require("common.pystring")
local CvProc = require("collector.vproc")
local root = "sys/fs/cgroup/cpuacct/"
local dfile = "/cpuacct.wait_latency"

local CgWaitLatency = class("cg_wait_latency", CvProc)

--ls{}, (pod_name and docker_name
function CgWaitLatency:_init_(proto, pffi, mnt, path, ls)
    CvProc._init_(self, proto, pffi, mnt, root .. path .. dfile)
	self.ls = ls
end

function CgWaitLatency:proc(elapsed, lines)
	-- if pFile not valid ,return -1
    local c = 1
    CvProc.proc(self)
    local values = {}

    for line in io.lines(self.pFile) do
        local cell = pystring:split(line)
	    local tmp = cell[1]
	    tmp = string.gsub(tmp, ":", "", 1)
	    tmp = string.gsub(tmp, ">=", "", 1)
	    tmp = string.gsub(tmp, "-", "to", 1)
	    tmp = string.gsub(tmp, "%(.*%)", "", 1)
        values[c] = {
            name = "wait_lat_"..tmp,
            value = tonumber(cell[2])
        }
        c = c + 1
    end
    self:appendLine(self:_packProto("cg_wait_latency", self.ls, values))
    self:push(lines)
end

return CgWaitLatency
