---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/29 12:54 AM
---

require("common.class")
local pystring = require("common.pystring")
local CvProc = require("collector.vproc")
local root = "sys/fs/cgroup/cpu/"
local dfile = "/cpu.stat"

local cgCpuStatSample = class("cg_cpu_stat_sample", CvProc)

function cgCpuStatSample:_init_(proto, pffi, mnt, path, ls)
    CvProc._init_(self, proto, pffi, mnt, root .. path .. dfile)
    self.ls = ls
end

function cgCpuStatSample:proc(elapsed, lines)
    local c = 1
    CvProc.proc(self)
    local values = {}

    for line in io.lines(self.pFile) do
        local cell = pystring:split(line)
        values[c] = {
            name = cell[1],
            value = tonumber(cell[2])
        }
        c = c + 1
        if c > 3 then
            break
        end
    end
    self:appendLine(self:_packProto("cg_cpu_stat", self.ls, values))
    self:push(lines)
end

return cgCpuStatSample