---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/15 6:00 PM
---

require("common.class")

local ChttpCli = require("httplib.httpCli")
local system = require("common.system")
local pystring = require("common.pystring")
local unistd = require("posix.unistd")

local CpodsApi = class("podsApi")

local function spiltConId(conId)
    local res = pystring:split(conId, "//", 1)
    return res[2]
end

local function getRuntime(mnt)
    if unistd.access(mnt .. "var/run/docker/runtime-runc/moby/") == 0 then
        return "docker"
    end
    return "cri-containerd"
end

local function joinNPath(cell, runtime)
    -- "/sys/fs/cgroup/cpu/kubepods.slice/kubepods-${qos}.slice/kubepods-${qos}-pod${podid}.slice/${runtime}-${cid}.scope"
    local paths = {
        "/kubepods.slice/kubepods-",
        cell.pod.qos,
        ".slice/kubepods-",
        cell.pod.qos,
        "-pod",
        cell.pod.uid,
        ".slice/",
        runtime,
        "-",
        cell.id,
        ".scope"
    }
    return pystring:join("", paths)
end

local function joinGPath(cell, runtime)
    -- "/sys/fs/cgroup/cpu/kubepods.slice/kubepods-pod${podid}.slice/${runtime}-${cid}.scope"
    local paths = {
        "/kubepods.slice/kubepods-pod",
        cell.pod.uid,
        ".slice/",
        runtime,
        "-",
        cell.id,
        ".scope"
    }
    return pystring:join("", paths)
end

local function joinPath(cell, runtime)
    if cell.pod.qos == "guaranteed" then
        return joinGPath(cell, runtime)
    else
        return joinNPath(cell, runtime)
    end
end

local function setupCons(res)
    local mnt = res.config.proc_path
    local runtime = getRuntime(mnt)
    local cli = ChttpCli.new()
    local cons = {}
    local c = 0

    local content = cli:get("http://127.0.0.1:10255/pods")
    local obj = cli:jdecode(content.body)

    for _, pod in ipairs(obj.items) do
        local metadata = pod.metadata
        local lpod = {name = metadata.name,
                      namespace = metadata.namespace,
                      uid = pystring:replace(metadata.uid, "-", "_"),
                      qos = pystring:lower(pod.status.qosClass),
        }

        local containerStatuses = pod.status.containerStatuses
        for _, con in ipairs(containerStatuses) do
            local cell = {
                pod = lpod,
                name = con.name,
                id = spiltConId(con.containerID)
            }
            cell.path = joinPath(cell, runtime)
            if unistd.access(mnt .. "sys/fs/cgroup/cpu/" .. cell.path) == 0 then
                c = c + 1
                cons[c] = cell
            end
        end
    end

    return cons
end

local function setupPlugins(res, proto, pffi, mnt)
    local c = 0
    local cons = setupCons(res)
    local plugins = {}

    for _, con in ipairs(cons) do
        local ls = {
            {
                name = "pod_name",
                index = con.pod.name,
            },
            {
                name = "con_name",
                index = con.name,
            },
            {
                name = "qos",
                index = con.pod.qos,
            },
            {
                name = "ns",
                index = con.pod.namespace,
            },
            {
                name = "uid",
                index = con.pod.uid,
            },
            {
                name = "con_id",
                index = con.id,
            },
        }

        for _, plugin in ipairs(res.container.luaPlugin) do
            local CProcs = require("collector.container." .. plugin)
            c = c + 1
            plugins[c] = CProcs.new(proto, pffi, mnt, con.path, ls)
        end
    end

    return plugins
end

function CpodsApi:_init_(resYaml, proto, pffi, mnt)
    self._plugins = setupPlugins(resYaml, proto, pffi, mnt)
    print( "pods plugin add " .. #self._plugins)
end

function CpodsApi:proc(elapsed, lines)
    local rec = {}
    for i, plugin in ipairs(self._plugins) do
        local res = plugin:proc(elapsed, lines)
        if res == -1 then
            table.insert(rec, i)
        end
    end

    for _, i in ipairs(rec) do  -- del bad plugin
        self._plugins[i] = nil
    end
end

return CpodsApi
