---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/15 2:16 AM
---

package.cpath = package.cpath .. ";../../beeQ/lib/?.so"
package.path = package.path .. ";../../?.lua;"

local CrbEvent = require("common/rbEvent")

local e = CrbEvent.new()

e:addEvent("test period 2", 2)
e:addEvent("test period 3", 3)
e:addEvent("stop period 3", 3, true, 10)

e:proc()