kmsg_log_list = [
    "Task in /(.+) killed as a result of limit of .*",
    "kernel has no deadlock",
    "unregister_netdevice: waiting for \\w+ to become free. Usage count = \\d+",
    "task umount\\.aufs:\\w+ blocked for more than \\w+ seconds\\.",
    "task docker:\\w+ blocked for more than \\w+ seconds\\.",
    "TCP: out of memory -- consider tuning tcp_mem",
    "TCP: too many orphaned sockets",
    "nf_conntrack: table full, dropping packet",
    "\\w+: neighbor table overflow!",
    "Buffer I/O error on device (.+), logical block \\d+",
    "EXT4-fs error .*",
    "blk_update_request: I/O error, dev \\w+, sector \\d+",
    "VFS: file-max limit \\d+ reached",
    "cache_from_obj: Wrong slab cache. (.+) but object is from (.+)",
    "page allocation failure(.) order:[3-5],(.+)",
    "BUG: soft lockup - CPU#\\d+ stuck for (.+)",
    "BUG: scheduling while atomic:(.+)",
    "INFO: \\w+ self-detected stall on CPU (.+)",
    "Card not present on Slot(.+)",
    "invoked oom-killer",
    "rcu_sched detected stalls",
    "BUG: scheduling while atomic",
    "EXT4-fs error",
    "EXT4-fs warning",
    "Buffer I/O error on device",
    "Remounting filesystem read-only",
    "blocked for more than"

]
