---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wrp.
--- DateTime: 2023/8/25 09:29
---

package.path = package.path .. ";../../../?.lua;"
local system = require("common.system")
local ChttpCli = require("httplib.httpCli")

local cli = ChttpCli.new()
local url = "http://127.0.0.1:8400/api/diag"

local header = {
    accept = "application/json",
    ["Content-Type"] = "application/json"
}
local body = {
    username = "admin",
    password = "123456"
}
local req = {host = "192.168.0.121", uri = "/api/v1/auth/", headers = header, body = body}
local res = cli:postTable(url, req)

system:dumps(res)