---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/5/24 11:21
---

package.path = package.path .. ";../../../?.lua;"
local psocket = require("posix.sys.socket")
local unistd = require("posix.unistd")
local pystring = require("common.pystring")
local system = require("common.system")

local function lookup_server()
    local f = io.open("/etc/resolv.conf")
    local server = ""
    for line in f:lines() do
        if pystring:startswith(line, "nameserver") then
            local res = pystring:split(line)
            server = res[2]
            break
        end
    end

    f:close()
    return server
end

function dns_lookup(domain_name)
    local fd = psocket.socket(psocket.AF_INET, psocket.SOCK_DGRAM, 0)
    local dst = lookup_server()
    local tDist = {family=psocket.AF_INET, addr=dst, port=53}

    local cnt = 0
    local queries = {}
    local head = string.char(
            0x12, 0x34, -- Query ID
            0x01, 0x00, -- Standard query
            0x00, 0x01, -- Number of questions
            0x00, 0x00, -- Number of answers
            0x00, 0x00, -- Number of authority records
            0x00, 0x00  -- Number of additional records
    )
    cnt = cnt + 1
    queries[cnt] = head

    local names = pystring:split(domain_name, ".")
    for _, name in ipairs(names) do
        cnt = cnt + 1
        queries[cnt] = string.char(string.len(name))
        cnt = cnt + 1
        queries[cnt] = name
    end
    cnt = cnt + 1
    local tail = string.char(
            0x00, -- End of domain name
            0x00, 0x01, -- Type A record
            0x00, 0x01 -- Class IN
    )
    queries[cnt] = tail

    local query = table.concat(queries)
    psocket.sendto(fd, query, tDist)
    local response = psocket.recvfrom(fd, 512)
    system:hexdump(response)
    unistd.close(fd)
    if response then
        local ip_address = string.format("%d.%d.%d.%d", string.byte(response, -4, -1))
        return ip_address
    else
        return nil
    end
end

local domain_name = "www.baidu.com"
local ip_address = dns_lookup(domain_name)
if ip_address then
    print(string.format("%s -> %s", domain_name, ip_address))
else
    print(string.format("Failed to resolve %s", domain_name))
end