---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wrp.
--- DateTime: 2023/7/17 09:45
---

require("common.class")

local CcoHttpCli = require("httplib.coHttpCli")

local CcoHttpCliInst = class("coHttpCliInst", CcoHttpCli)

function CcoHttpCliInst:_init_(instance, pushTo, persistent)
    CcoHttpCli._init_(self, pushTo ,persistent)

    self._instance = instance
end

function CcoHttpCliInst:addInstance(line)   -- add instance id for line index.
    local cells = line.ls
    local hasInstance = false

    if cells then
        for _, cell in ipairs(cells) do
            if cell.name == "instance" then
                hasInstance = true
            end
        end
    end

    if not hasInstance then
        local cell = {
            name = "instance",
            index = self._instance
        }
        if cells then
            table.insert(cells, cell)
        else
            line.ls = {cell}
        end
    end
end

return CcoHttpCliInst