---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/11/22 6:03 PM
---

require("common.class")
local lineParse = require("common.lineParse")

local coSls = require("httplib.coSls")
local CcoSlsMetric = class("CcoSlsLog", coSls)

function CcoSlsMetric:_init_(fYaml, config, instance)
    coSls._init_(self, fYaml, config, instance)
end

function CcoSlsMetric:transLine(line)
    return lineParse.packMetric(line)
end

return CcoSlsMetric
