---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/23 11:53 PM
---

require("common.class")
local pystring = require("common.pystring")
local ChttpBase = require("httplib.httpBase")

local ChttpHtml = class("ChttpHtml", ChttpBase)

function ChttpHtml:_init_(frame)
    ChttpBase._init_(self)
end

function ChttpHtml:markdown(text)
    local md = require("common.lmd")
    return md:toHtml(text)
end

local function htmlPack(title, content)
    local h1 = [[
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>]]
    local h2 = [[</title>
</head>

<body>
]]
    local h3 = [[
</body>

</html>
]]

    local bodies = {h1, title, h2, content, h3}
    return pystring:join("", bodies)
end

function ChttpHtml:echo(tRet, keep)
    local stat = self:packStat(200)
    local tHead = {
        ["Content-Type"] = "text/html",
        ["Connection"] = (keep and "keep-alive") or "close"
    }
    local body = htmlPack(tRet.title, tRet.content)
    local headers = self:packHeaders(tHead, #body)
    local tHttp = {stat, headers, body}
    return pystring:join("\r\n", tHttp)
end

return ChttpHtml
