---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wrp.
--- DateTime: 2023/7/17 15:42
---

local ts = io.popen('curl 100.100.100.200/latest/meta-data/region-id')
local s = ts:read("*all")
print("s    "..s)
