---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:39 PM
---

require("class")
local CprotoData = require("protoData")
local procffi = require("procffi")

local CprocStat = require("proc_stat")
local CprocMeminfo = require("proc_meminfo")
local CprocVmstat = require("proc_vmstat")
local CprocNetdev = require("proc_netdev")
local CprocDiskstats = require("proc_diskstats")

local Cloop = class("loop")

function Cloop:_init_()
    self._proto = CprotoData.new()
    self._procs = {
        CprocStat.new(self._proto, procffi),
        CprocMeminfo.new(self._proto, procffi),
        CprocVmstat.new(self._proto, procffi),
        CprocNetdev.new(self._proto, procffi),
        CprocDiskstats.new(self._proto, procffi),
    }
end

function Cloop:work(t)
    local lines = {}
    for k, obj in pairs(self._procs) do
        local res = obj:proc(t)
        table.insert(lines, res)
    end
    print(#lines, #lines[4], #lines[5])
    print(collectgarbage("count"))
end

return Cloop
