---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/21 12:08 AM
---
---

require("common.class")
local CvProc = require("collector.vproc")

local CprocBled = class("procArp", CvProc)

function CprocBled:_init_(proto, pffi, mnt, pFile)
    --CvProc._init_(self, proto, pffi, mnt, pFile or "dummy")
    CvProc._init_(self, proto)
    print("a")

    self._record = 1
end

function CprocBled:proc(elapsed, lines)
    print("this only a test case for bled " .. self._record)
    self._record = self._record + 1
    if self._record > 5 then
        print("trig full cpu.")
        local t = os.time() + 2
        while os.time() < t do
            local c = 1
        end
    end
end

return CprocBled
