---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 11:36 PM
---

require("class")
local CkvProc = require("kvProc")

local CprocMeminfo = class("proc_meminfo", CkvProc)

function CprocMeminfo:_init_(proto, pffi, pFile)
    CkvProc._init_(self, proto, pffi, pFile or "/proc/meminfo", "meminfo")
end

return CprocMeminfo