---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/7 2:30 PM
---

require("common.class")
local pystring = require("common.pystring")
local CvProc = require("collector.vproc")

local CprocArp = class("procArp", CvProc)

function CprocArp:_init_(proto, pffi, mnt, pFile)
    CvProc._init_(self, proto, pffi, mnt, pFile or "proc/net/arp")
end

function CprocArp:proc(elapsed, lines)
    local c = 0
    CvProc.proc(self)
    local arps = {}
    for line in io.lines(self.pFile) do
        if c > 0 then
            local cells = pystring:split(line)
            if arps[cells[6]] then
                arps[cells[6]] = arps[cells[6]] + 1
            else
                arps[cells[6]] = 1
            end
        end
        c = c + 1
    end

    for k, v in pairs(arps) do
        local ls = {}
        ls = {
            name = "dev",
            index = k,
        }
        local vs = {}
        vs = {
            name = "count",
            value = v,
        }
        self:appendLine(self:_packProto("arp", {ls}, {vs}))
    end
    self:push(lines)
end

return CprocArp