---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:12 PM
---

require("class")

local CvProc = class("vproc")

function CvProc:_init_(proto, pffi, pFile)
    self._proto = proto
    self._cffi = pffi["cffi"]
    self._ffi = pffi["ffi"]
    self.pFile = pFile
    print(pFile)
end

function CvProc:proc(elapsed)
    self._lines = self._proto:protoTable()
end

function CvProc:appendLine(line)
    table.insert(self._lines["lines"], line)
end

function CvProc:push()
    local bytes = self._proto:encode(self._lines)
    self._lines = nil
    return bytes
end

function CvProc:_packProto(head, labels, vs, log)
    return {line = head, ls = labels, vs = vs, log = log}
end

return CvProc