---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:12 PM
---

require("common.class")
local system = require("common.system")

local CvProc = class("collector.vproc")

function CvProc:_init_(proto, pffi, mnt, pFile)
    self._proto = proto
    self._cffi = pffi["cffi"]
    self._ffi = pffi["ffi"]
    mnt = mnt or "/"
    pFile = pFile or ""
    self.pFile = mnt .. pFile
end

function CvProc:proc(elapsed)
    self._lines = self._proto:protoTable()
end

function CvProc:appendLine(line)
    table.insert(self._lines["lines"], line)
end

function CvProc:copyLine(line)
    self:appendLine(system:deepcopy(line))
end

function CvProc:push(lines)
    for _, v in ipairs(self._lines["lines"]) do
        table.insert(lines["lines"], v)
    end
    self._lines = nil
    return lines
end

function CvProc:_packProto(head, labels, vs, log)
    return {line = head, ls = labels, vs = vs, log = log}
end

return CvProc