---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/20 1:24 AM
---

local CurlApi = require("urlApi")
local Cframe = require("frame")

function init()
    frame = Cframe.new()
    local api = CurlApi.new(frame)
    api:setup()
    print("hello new beaver.")
end

function echos(conn, tParam)
    frame:echos(conn, tParam)
end
