---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/29 2:03 PM
---

package.path = package.path .. ";../../?.lua"

local exec = require("common.exec")
local unistd = require("posix.unistd")
local pwait = require("posix.sys.wait")

local fIn, fOut = unistd.pipe()
assert(fIn, "creat pipe failed.")

local pid = exec.run("/bin/ls", {"-l"}, fIn, fOut)
pwait.wait(pid)
print("child say:\n" .. unistd.read(fIn, 1024))