---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/20 2:47 PM
---

package.path = package.path .. ";../../?.lua;"

local inotify = require('inotify')
local system = require("common.system")

local handle = inotify.init()
local w = handle:addwatch("./test.txt", inotify.IN_MODIFY)

while true do
    for e in handle:events() do
        system:dumps(e)
    end
    system:sleep(1)
end
