---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/19 5:55 PM
---

package.path = package.path .. ";../../?.lua;"

require("common.class")
local system= require("common.system")

local Cone = require("one")
local Ctwo = require("two")
local CThree = require("three")

local one = Cone.new("1one")
local two = Ctwo.new("2two")
local three = CThree.new("3three")

print(one:hello())
assert(one:hello() == "1one")
assert(two:hello() == "2two")
assert(three:hello() == "3three")

one:say()
two:say()
three:say()

one = nil
two:say()