---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/25 8:05 PM
---

package.path = package.path .. ";../../?.lua;"

local system = require("common.system")

local len = 32
local s = system:randomStr(len)
assert(#s == len)
print(s)
