---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/8 01:01
---

require("struct")

local s = struct.pack("<i", 1024)
print(#s)
local len = struct.unpack("<i", s)
print(len)