---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/29 9:25 PM
---

package.path = package.path .. ";../../?.lua;"

local CfifoNum = require("common.fifoNum")
local system = require("common.system")

local fifo = CfifoNum.new(4)

for i = 1, 100 do
    fifo:push(i)
end

local res, index
res, index = fifo:min()
assert(res == 97)
assert(index == 1)
print(fifo:value(index))
assert(res == fifo:value(index))

res, index = fifo:max()
assert(res == 100)
assert(index == 4)

res = fifo:sum()
assert(res == 394)

res = fifo:average()
assert(res == 98.5)

local v = fifo:pop()
while v do
    print(v)
    v = fifo:pop()
end
