---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/4/10 00:10
---

package.path = package.path .. ";../../?.lua;"

local Ciplib = require("common.iplib")

local route = Ciplib.new("/mnt/host/")
print(string.format("0x%x", route:toInt("172.16.0.1")))
print(route:routeIp("172.17.0.188"))
print(route:routeIp("8.8.8.8"))

