---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/28 11:38 PM
---

package.path = package.path .. ";../../?.lua;"

local system = require("common.system")
local CpodFilter = require("collector.podMan.podFilter")

local resYaml = system:parseYaml("podFilter.yaml")
local filter = CpodFilter.new("/mnt/host/sys/fs/cgroup")
local ret = filter:walkTops(resYaml)
print(#ret)
