netobser:
  proto:["http","dns","redis","mysql"]
  pid:-1
  port:-1
  sample:100
- name: nginx
  #format: $remote_addr - $remote_user [$time_local] "$method $request $protocol" $request_time-$upstream_response_time $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_id
  format: $remote_addr - $remote_user [$time_local] "$request" $status $request_time $upstream_response_time $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"
  source_files:
    - /var/log/nginx/access.log
  external_labels:
    region: 101.200.151.112
  relabel_config:
    source_labels:
      - request
      - method
      - status
    replacement:
      request:
        trim: "?"
        replace:
          - target: /v1.0/example/\d+
            value: /v1.0/example/:id
      status:
        replace:
          - target: 2.+
            value: 2xx
          - target: 3.+
            value: 3xx
          - target: 4.+
            value: 4xx
          - target: 5.+
            value: 5xx
  histogram_buckets: [0.1, 0.3, 0.5, 1, 2]
  exemplar_config:
    match:
      request_time: ">= 0.3"
    labels:
      - request_id
      - remote_addr
