---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/8/15 10:40 AM
---

package.path = package.path .. ";../../?.lua"

local CfoxTSDB = require("tsdb.foxTSDB")
local system = require("common.system")

local fYaml = "fox.yaml"

local rdb = CfoxTSDB.new(fYaml)
local res = {}

rdb:_setupRead()
rdb:qlast(5, res)
assert(#res >= 4)

system:sleep(5)
print("after.")
rdb:resize()
res = {}
rdb:qlast(6, res)
assert(#res >= 5)
print("db query test ok.")
