---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/1/27 10:08 PM
---

local dirent = require("posix.dirent")
local unistd = require("posix.unistd")

local ok, files = pcall(dirent.files, '../')
if not ok then
    print('/var/log: ' .. files)
end

local year = 122
local mon  = 11
local mday = 20
local level = year * 10000 + mon * 100 + mday
for f in files do
    if string.match(f,"^%d%d%d%d%d%d%d%d%.fox$") then
        local sf = string.sub(f, 1, 8)
        local num = tonumber(sf)
        if num < level then
            print(num)
        end
        --pcall(unistd.unlink, "../" .. f)
    end
end