---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/2/13 10:26 PM
---

package.path = package.path .. ";../../../?.lua;"

local CpoBeaver = require("poBeaver")

local bserver = CpoBeaver.new()
bserver:poll()
